api:
  swagger:
    swaggerPath: classpath:api/revocation-service-api.yml
  security:
    oauth2-scopes:
# Until scope token.revoke is not in YourTurn we cannot use this rule...
#      revokeStandard: "#oauth2.hasScope('uid') && #oauth2.hasScope('token.revoke') && (#oauth2.hasRealm('/services') || #oauth2.hasRealm('/employees'))"
      revokeStandard: "#oauth2.hasScope('uid') && (#oauth2.hasRealm('/services') || #oauth2.hasRealm('/employees'))"

cassandra:
  keyspace: revocation

security:
  oauth2:
    resource:
      # Get Environment variable
      tokenInfoUri: ${TOKENINFO_URL}

management:
  port: 7979
  security:
    enabled: false

server:
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain

---

spring:
  profiles: it

cassandra:
  contactPoints: 127.0.0.1
  clusterName: Local Cluster

security:
  oauth2:
    resource:
      tokenInfoUri: "http://localhost:${wiremock.port:10080}/tokeninfo"

logging:
  level:
    de.zalando.planb.revocation: DEBUG
    org.apache.http: DEBUG
    org.apache.http.wire: DEBUG

server:
  compression:
    min-response-size: 100

---

spring:
  profiles: local

security:
  oauth2:
    resource:
      tokenInfoUri: "https://auth.zalando.com/z/oauth2/tokeninfo"
