api:
  swagger:
    swaggerPath: classpath:api/revocation-service-api.yml
  security:
    oauth2-scopes:
      revokeStandard: "#oauth2.hasScope('uid') && #oauth2.hasScope('token.revoke') && #oauth2.hasRealm('/services')"
      readApi: "#oauth2.hasScope('uid') && #oauth2.hasRealm('/services')"
      write: "#oauth2.hasScope('uid') && #oauth2.hasRealm('/services')"

cassandra:
  keyspace: revocation
  contactPoints: ${CASSANDRA_HOSTS}
  clusterName: Local Cluster

security:
  oauth2:
    resource:
      tokenInfoUri: ${TOKENINFO_URI}

management:
  port: 7979
  security:
    enabled: false

---

spring:
  profiles: it

cassandra:
  contactPoints: 127.0.0.1
  clusterName: Local Cluster

security:
  oauth2:
    resource:
      tokenInfoUri: "http://localhost:${wiremock.port:10080}/tokeninfo"

logging:
  level:
    de.zalando.planb.revocation: DEBUG

---

spring:
  profiles: local

cassandra:
  contactPoints:

security:
  oauth2:
    resource:
      tokenInfoUri: "https://auth.zalando.com/z/oauth2/tokeninfo"
