api:
  security:
    oauth2-scopes:
      revokeStandard: "#oauth2.hasScope('uid') && (#oauth2.hasRealm('/services') || #oauth2.hasRealm('/employees'))"

security:
  oauth2:
    resource:
      # Get Environment variable
      tokenInfoUri: ${TOKENINFO_URL}

management:
  port: 7979
  security:
    enabled: false

server:
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain

revocation:
  hashing:
    algorithms:
      TOKEN: SHA-256
      CLAIM: SHA-256
    salt: seasaltisthebest